services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/cache/cache.conf
    env_file: ".env"
    command: ["redis-server", "--requirepass", "$REDIS_PASSWORD"]