services:
  assets:
    build: .
    ports:
      - "4000:8000"
    volumes:
      - ../../../src/assets:/src/assets/
      - ../../../src/utils:/src/utils/
      - ../../../src/app.py:/app.py
      - user_data:/user_data
    env_file: ".env"
    command: [ "hypercorn", "-b", "0.0.0.0:8000", "app:create_app()" ]
    restart: always
volumes:
  user_data: